### ISSUE TITLE
Need more flexible configuration

### ISSUE THREAD

**Issue by chobostar** [hazelcast/hazelcast-platform-operator#302]
Currently CRDs doesn't support all available configuration

for example:
```
    jmx:
       enabled: true
       collection-frequency-seconds: 5
    cache:
        name: 'HibernateL2.*'
        statistics-enabled: true
        management-enabled: true
        in-memory-format: BINARY
        backup-count: 1
        async-backup-count: 0
        eviction:
            size: 1000
            max-size-policy: ENTRY_COUNT
            eviction-policy: LFU
```

Could operator support external ConfigMap - like it was done in redis-operator?

example:
https://github.com/OT-CONTAINER-KIT/redis-operator/blob/v0.11.0/config/crd/bases/redis.redis.opstreelabs.in_redis.yaml#L1295-L1300

https://github.com/OT-CONTAINER-KIT/redis-operator/blob/v0.11.0/example/external_config/standalone.yaml#L7-L8
https://github.com/OT-CONTAINER-KIT/redis-operator/blob/v0.11.0/example/external_config/configmap.yaml#L5
