### ISSUE TITLE
[Question] How to Add/Update Hazelcast config through the operator/ Hazelcast CRD

### ISSUE THREAD

**Issue by bokjo** [hazelcast/hazelcast-platform-operator#384]
Hello all,

Maybe not the right place to ask this one.

Is there a way to add/update the Hazelcast config through the Hazelcast CRD somehow, I'm seeing just predefined options in the spec that are available.

For example disabling `Jet` in the CRD, since it is enabled by default?

Editing the ConfigMap after the cluster is created is picked up by the operator controller but nothing is happening (reconciling on StatefulSet side)... manually restarting the cluster StatefulSet doesn't pick up the manually updated ConfigMap.

```json
{"level":"info","ts":1665067430.970415,"logger":"controllers.Hazelcast","msg":"Operation result","hazelcast":"hazelcast/hz","ConfigMap":"hz","result":"updated"}
```

Seems there is no way to set the `near-cache` options in the `Map` CRD, is this by design or there is some other way to do it?

Also, I'm using tools like `crd2pulumi` to generate code from the CRDs and is was failing because there were default values for object types  like 

```yaml
          spec:
            # default: # NOTE: Che hack - removed because crd2pulumi was failing
            #   repository: docker.io/hazelcast/hazelcast
            description: HazelcastSpec defines the desired state of Hazelcast
            properties:
              agent:
                # default: # NOTE: Che hack - removed because crd2pulumi was failing
                #   repository: docker.io/hazelcast/platform-operator-agent
                #   version: 0.1.6
                description: B&R Agent configurations
```
is this a good place to report those, think they are not actually needed!

Thanks in advance
@bokjo
