### ISSUE TITLE
kubernetes operator: delete of CRs hangs on finalizer - sometimes

### ISSUE THREAD

**Issue by axelsean** [hazelcast/hazelcast-platform-operator#651]
When deleting the CRs, from the kubernetes operator, the delete hangs on finalizers - around 25% of time.  This is in Azure.

**Background:**

Our application uses hazelcast to cache:
- maps
- java objects

When the application is upgraded there's a blue/green upgrade, scale down the blue, deploy green (test), delete blue (if all good).  On the scale down the CRs are deleted (not tried patching clusterSize to zero).  It's this delete that hangs.

The clusters in Azure usually have multiple namespaces defined, each namespace is a full application, thus the CRD is shared (since this doesn't seem to be namespaced).   Each namespace is upgraded separately.

The issue is not multiple versions of hazelcast - that's hard coded - see below.

There's a secondary use case (for our develoment builds) where we also delete the whole application and the namespace - same STR and frequency of failure.

**Expected behavior**
The CRs are deleted

**To Reproduce**

- delete the hazelcast CR
- delete the management CR
- (optional) delete the namespace

```bash
kubectl delete managementcenters.hazelcast.com/ams-hazelcast-managementcenter-blue -n my-namespace
kubectl delete Hazelcast/ams-hazelcast-blue  -n my-namespace
```
.

**Additional context**

We've observed 3 cases of issue:

- the hazelcast CR hangs and it has a finalizer
- the management CR hangs and it has a finalizer
- when deleting the namespace it hangs and we have to remove the finalizer

**Work Arounds**

For the CRs, we have patched to remove the finalizer, this 

```bash
kubectl patch Hazelcast/ams-hazelcast-blue -n my-namespace -p '{"metadata":{"finalizers":[]}}' --type=merge
kubectl patch managementcenters/ams-hazelcast-managementcenter-blue -n my-namespace -p '{"metadata":{"finalizers":[]}}' --type=merge

```

For the namespace issue
```bash
kubectl get namespace my-namespace -o json   | tr -d "\n" | sed "s/\"finalizers\": \[[^]]\+\]/\"finalizers\": []/"   | kubectl replace --raw /api/v1/namespaces/my-namespace/finalize -f -

```

One result we observed:

```bash
get namespace my-namespace -o json 
{
    "apiVersion": "v1",
    "kind": "Namespace",
    "metadata": {
        "annotations": {
            "kubectl.kubernetes.io/last-applied-configuration": "{\"apiVersion\":\"v1\",\"kind\":\"Namespace\",\"metadata\":{\"annotations\":{},\"name\":\"ams-hazelcast2-nonprod\"}}\n"
        },
        "creationTimestamp": "2023-03-02T17:30:43Z",
        "labels": {
            "kubernetes.io/metadata.name": "ams-hazelcast2-nonprod"
        },
        "name": "my-namespace",
        "resourceVersion": "3304666",
        "uid": "466da2a1-a4bf-497a-9b64-dfc9d082784f"
    },
    "spec": {
        "finalizers": [
            "kubernetes"
        ]
    },
    "status": {
        "phase": "Active"
    }
}
```

**CR definiitions**

setup:
```yaml
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: 'my-namespace'
#
# See also https://docs.hazelcast.com/operator/latest/get-started
#
resources:
  - https://repository.hazelcast.com/operator/bundle-5.5.yaml
```
hazelcast CR
 
```yaml
apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: ams-hazelcast-@SLOT@
  namespace: '@STACK_NAMESPACE@'         
spec:                                    
  clusterSize: 3                         
  clusterName: ams-hazelcast-cluster-@SLOT@
  repository: 'docker.io/hazelcast/hazelcast'
  version: '5.1.4'
  exposeExternally:                      
    memberAccess: LoadBalancer      
    type: Smart                           
    discoveryServiceType: NodePort
  loggingLevel: INFO
  properties:                                   
    hazelcast.jmx: "true"
    hazelcast.shutdownhook.policy: TERMINATE      # Default - GRACEFUL waits for closedown - could be blocked on finalizer
    hazelcast.shutdownhook.enabled: "true"
    hazelcast.graceful.shutdown.max.wait: "600"
```

ManagementCenter CR

```yaml
apiVersion: hazelcast.com/v1alpha1
kind: ManagementCenter
metadata:
  name: ams-hazelcast-managementcenter-blue
  namespace: 'my-namespace'
spec:
  repository: 'hazelcast/management-center'
  version: '5.1.4'
  externalConnectivity:
    type: LoadBalancer
  hazelcastClusters:
    - address: ams-hazelcast-blue
      name: ams-hazelcast-cluster-blue
  persistence:
    enabled: true
    size: 10Gi
```
