### ISSUE TITLE
IPV6 issue with ManagementCenter

### ISSUE THREAD

**Issue by sylvaindd** [hazelcast/hazelcast-platform-operator#758]
Hi,

I can't find out how to configure ManagementCenter to make it work with IPV6.
I have an IPV6 only EKS (AWS K8S) cluster (pods do have an IPV4 interface to join internet).

The probe on 8081 port fails because ManagementCenter doesn't listen on the IPV6 interface (I guess).
I didn't find a way to change the probe or anything that could make this work.

I am using 5.7.0 operator version with 5.3.0 Hazelcast/ManagementCenter

```yaml
apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: hazelcast-app
spec:
  clusterSize: 3
  version: '5.3.0'
  clusterName: app
  jvm:
    args:
      - "-Djava.net.preferIPv4Stack=false -XX:MaxRAMPercentage=80.0 -XX:MaxGCPauseMillis=5 -Djava.net.preferIPv6Addresses=true -Dhz.network.rest-api.enabled=true -Dhazelcast.prefer.ipv4.stack=false -Dhazelcast.socket.bind.any=false"

---

apiVersion: hazelcast.com/v1alpha1
kind: ManagementCenter
metadata:
  name: hazelcast-man-center-app
spec:
  version: '5.3.0'
  hazelcastClusters:
    - name: app
      address: hazelcast-app
```

Pertinent log : Hazelcast Management Center successfully started at http://localhost:8080

From inside the container, I can curl localhost:8080 / 8081 but I get a connection refused on [IPV6]:8080 / 8081

**Comment by sylvaindd** [comment]
Hi @dzeromski-hazelcast, I can't join the slack.
Unfortunately, dual stack isn't possible.
I guess that adding the jvm properties configuration in the ManagementCenter kind (as it is possible with Hazelcast kind) would solve the issue.
I managed to make it work with the helm chart by overriding the javaOpts the same way I did for Hazelcast.

**Comment by sylvaindd** [comment]
> We plan to release shortly and this change should be included. I will ping you when PR is ready.

Hi @dzeromski-hazelcast, any news regarding this ?

I'm also facing another issue with IPV6 and hazelcast cluster, the operator is complaining about "too many colons in address" :
```json
{"level":"info","ts":1688627259.226644,"logger":"client.hazelcast-app","msg":"connecting member 2a05:d012:1e9:4506:9d89:0:0:2c:5701:01a7a3f4-1ed3-4c90-ad41-6aa396a5354d: cannot connect to address in the cluster: dial tcp: address 2a05:d012:1e9:4506:9d89:0:0:2c:5701: too many colons in address: dial tcp: address 2a05:d012:1e9:4506:9d89:0:0:2c:5701: too many colons in address","Hazelcast":"hazelcast-app","Cluster":"app","Weight":"error"}
{"level":"info","ts":1688627260.2270103,"logger":"client.hazelcast-app","msg":"cannot connect to 2a05:d012:1e9:4506:9d89:0:0:2c:5701: dial tcp: address 2a05:d012:1e9:4506:9d89:0:0:2c:5701: too many colons in address: dial tcp: address 2a05:d012:1e9:4506:9d89:0:0:2c:5701: too many colons in address","Hazelcast":"hazelcast-app","Cluster":"app","Weight":"error"}
```

I think that's why some pods won't connect to the cluster, however, after deleting the problem pods a few times, it usually get them to connect for some reason.

**Comment by sylvaindd** [comment]
Hi @semihbkgr 

Thank you, I will try it once released.

Should I open a new issue for the problems (mentioned in my message above) I have encountered with IPV6 and the operator ?

**Comment by semihbkgr** [comment]
It seems these two issues are not related with each. So, would be better to create new separate issue.
In this way, we will be able to refer to this specific IPV6 issue which you mentioned in the comment above.

**Comment by semihbkgr** [comment]
@sylvaindd You are probably aware of that but I want heads you up anyway.
The Hazelcast CR config that you gave in the first [issue description](https://github.com/hazelcast/hazelcast-platform-operator/issues/758#issue-1748083626) is incorrect. It should be in a way that each JVM args is passed as an item of array.

```yaml
jvm:
    args:
      - "-Djava.net.preferIPv4Stack=false"
      - "-XX:MaxRAMPercentage=80.0"
      - "-XX:MaxGCPauseMillis=5"
      - "-Djava.net.preferIPv6Addresses=true"
      - "-Dhz.network.rest-api.enabled=true"
      - "-Dhazelcast.socket.bind.any=false"
```
