### ISSUE TITLE
Allow Addition Of Environment Variables For Man Center Through Operator

### ISSUE THREAD

**Issue by afoley-st** [hazelcast/hazelcast-platform-operator#836]
We have a use case to set the `MC_CONTEXT_PATH` environment variable for our management center UI since it sits behind a reverse proxy.

There doesnt seem to be a way to add `MC_` variables in the management center CRD's. 

Please advise!

**Comment by semihbkgr** [comment]
Hi @afoley-st 

We have implemented `jvm.args` field which let you set custom JVM args in ManagementCenter CRD. You can use System Properties to configure `context path` of Mancenter. It will be available in the next release (version 5.9).

```yaml
kind: ManagementCenter
spec:
  ...
  jvm:
    args:
      - '-Dhazelcast.mc.contextPath=hazelcast-mc'
```
