### ISSUE TITLE
HZ cluster failed if 'hotBackupResourceName' is wrong [CN-975]

### ISSUE THREAD

**Issue by SeriyBg** [hazelcast/hazelcast-platform-operator#889]
1. Create HZ cluster
```
apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: hazelcast
spec:
  clusterSize: 3
  repository: "docker.io/hazelcast/hazelcast-enterprise"
  licenseKeySecretName: hazelcast-license-key
  exposeExternally:
    discoveryServiceType: LoadBalancer
    memberAccess: NodePortExternalIP
  persistence:
    baseDir: "/data/hot-restart/"
    clusterDataRecoveryPolicy: "PartialRecoveryMostComplete"
    pvc:
      accessModes: ["ReadWriteOnce"]
      requestStorage: 20Gi
```

2. Apply Cronbackup CR
```
apiVersion: hazelcast.com/v1alpha1
kind: CronHotBackup
metadata:
  name: cron-hot-backup
spec:
  schedule: "* * * * *"
  suspend: false
  successfulHotBackupsHistoryLimit: 2
  hotBackupTemplate:
    spec:
      hazelcastResourceName: hazelcast
```

3. Delete HZ cluster by removing HZ CR

4. Update hotBackupResourceNamewith an incorrect non-existing backup name. Let’s say the user thought that it should be the CronHotBackup CR name instead of the backup name.
```
apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: hazelcast
spec:
  clusterSize: 3
  repository: 'docker.io/hazelcast/hazelcast-enterprise'
  licenseKeySecretName: hazelcast-license-key
  persistence:
    baseDir: "/data/hot-restart/"
    clusterDataRecoveryPolicy: "PartialRecoveryMostComplete"
    pvc:
      accessModes: ["ReadWriteOnce"]
      requestStorage: 20Gi
    restore:
      hotBackupResourceName: cron-hot-backup
  agent:
    repository: hazelcast/platform-operator-agent
```

5. Check the Operator logs

**ER**:
It should be some validation if the user try to apply and use a resource name that doesn’t exist. 
User should see the error immediately and understand what is happening without digin into the Operator logs.

**AR**:
HZ cluster didn’t create BUT CR applied and didn’t throw any error. Only checking Operator logs makes it a bit clear what is wrong.
```
{"level":"error","ts":1693398806.7268736,"msg":"Reconciler error","controller":"hazelcast","controllerGroup":"hazelcast.com","controllerKind":"Hazelcast","Hazelcast":{"name":"hazelcast","namespace":"default"},"namespace":"default","name":"hazelcast","reconcileID":"8de53cff-1dab-4418-8b7f-cd8beedc1318","error":"HotBackup.hazelcast.com \"cron-hot-backup\" not found","stacktrace":"sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:326\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:273\nsigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func2.2\n\t/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.13.1/pkg/internal/controller/controller.go:234"}
```
