### ISSUE TITLE
Specify limits for sidecar-agent

### ISSUE THREAD

**Issue by forti4our** [hazelcast/hazelcast-platform-operator#927]
Hi,

I have an issue to configure the limits for the sidecar-agent.
After applying the YAML file of operator it's not possible to set up limit for sidecar-agent.
Operator removes this section and only applies container section for cluster, even if I try to configure this for "sidecar-agent" and "hazelcast"separately.

Error:
`create Pod hazelcast-cluster-0 in StatefulSet hazelcast-cluster failed error: pods "hazelcast-cluster-0" is forbidden: failed quota: hazelcast-limit-rq: must specify limits.cpu for: sidecar-agent; limits.memory for: sidecar-agent; requests.cpu for: sidecar-agent; requests.memory for: sidecar-agent`

Is there any way to define limits for sidecar-agent in openshift for hazelcast-platofrm-operator ?
I can see I can change it only in alredy created  Statefullset, when manually adding it to the resources:

`          image: 'docker.io/hazelcast/hazelcast:5.3.2-slim'
        - resources: {}
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          terminationMessagePath: /dev/termination-log
          name: sidecar-agent
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
              scheme: HTTP
            timeoutSeconds: 10
            periodSeconds: 10
            successThreshold: 1
            failureThreshold: 10`

**Comment by hasancelik** [comment]
Hi @forti4our,

Thanks for the issue.

I agree with you we need to give this functionality to our users:

```
apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: hazelcast
spec:
  ...
  agent: 
    repository: hazelcast/platform-operator-agent
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
```
We will prioritize this enhancement for the upcoming release - 5.11.0.
