### ISSUE TITLE
Wrong annotation when using Smart client with no MemberAccess defined.

### ISSUE THREAD

**Issue by mtyazici** [hazelcast/hazelcast-platform-operator#95]
Default value for `memberAccess` is `NodePortExternalIP`. However when I supply the following Hazelcast CR:

```yaml
apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: hazelcast
spec:
  clusterSize: 3
  repository: 'docker.io/hazelcast/hazelcast-enterprise'
  version: '5.0'
  licenseKeySecret: hazelcast-license-key
  exposeExternally:
    type: Smart
    discoveryServiceType: LoadBalancer
```

The annotation for the memberAccess in Hazelcast pods becomes 

```yaml
metadata:
  annotations:
    hazelcast.com/expose-externally-member-access: ""
```

We need to set the default value for the memberAccess when Smart client is enabled.
