### ISSUE TITLE
Error: when Hazelcast Enterprise is deployed, licenseKeySecret must be set

### ISSUE THREAD

**Issue by jerrinot** [hazelcast/hazelcast-platform-operator#98]
Hello, I deployed [this version](https://repository.hazelcast.com/operator/bundle-5.0.yaml) of the Operator. 
This is how my resource definitions looks like:
```
15:00 $ cat hazelcast.yaml 
apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: hz-hazelcast
spec:
  version: "5.0.2-slim"
```
Hazelcast is NOT deployed and I can see the platform controller manager has this in its log:
```
2022-01-03T13:56:30.285Z	ERROR	controller-runtime.manager.controller.hazelcast	Reconciler error	{"reconciler group": "hazelcast.com", "reconciler kind": "Hazelcast", "name": "hz-hazelcast", "namespace": "default", "error": "when Hazelcast Enterprise is deployed, licenseKeySecret must be set"}
github.com/go-logr/zapr.(*zapLogger).Error
	/go/pkg/mod/github.com/go-logr/zapr@v0.2.0/zapr.go:132
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:302
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).processNextWorkItem
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:253
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Start.func1.2
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.8.3/pkg/internal/controller/controller.go:216
k8s.io/apimachinery/pkg/util/wait.JitterUntilWithContext.func1
```

This is a very basic scenario yet it does not appear to work. What am I doing wrong?

**Comment by jerrinot** [comment]
When I change the CR to:
```
15:25 $ cat hazelcast.yaml 
apiVersion: hazelcast.com/v1alpha1
kind: Hazelcast
metadata:
  name: hz-hazelcast
spec:
  repository: "hazelcast/hazelcast"
  version: "5.0.2-slim"
```
then it appears to work. It seems the operator defaults to Hazelcast EE, but Getting Started is assuming it defaults to OSS?
